export const en = {
    listFacts: [
        "Vietnam is leading in global crypto adoption, according to Chainalysis.",
        "Vietnam ranks first in crypto adoption, according to Finder's survey.",
        "Chainalysis reports that Vietnam ranks second, just behind the US, in DeFi adoption.",
        "Vietnam has the third largest number of monthly Metamask users globally.",
        "Founded in 2017, Coin68 is currently the largest crypto media organization in Vietnam.",
        "Coin68.com has over 15,000 articles and news covering blockchain.",
        "Kyros Ventures provides quarterly market reports and weekly research articles.",
        "Coin68 and Kyros Ventures conduct the largest official cryptocurrency survey in Vietnam."
    ],
    listSection: [
        "Welcome",
        "We are Kyros",
        "Our Pillars",
        "Our Team",
        "Contact us",
    ],
    nurture: `we nurture <span class="text-stroke" style="--width: 2px">early-stage talent</span><br />
    to bring in <span class="text-stroke" style="--width: 2px">the next wave</span> <br>
    of blockchain innovation.`,
    weAre: ` we are the gateway of<br />
    accessibility to
    <span class="text-stroke" style="--width: 2px">vietnam</span>,<br />
    <span class="text-stroke" style="--width: 2px"> the fastest-growing </span>
    <br />
    crypto market in the world.`,
    ourPillarTitle: 'our <span class="text-stroke font-extrabold" style="--width: 2px">pillars</span>',
    network: `<div class="mb-5">
                We leverage the largest crypto network in <span class="underline highlight"><a href="https://vcmr.kyros.ventures/h1-2022-en/" target="_blank">VIETNAM</a></span>, to help projects access one of the most dynamic markets in the world.
            </div>
            <div class="mt-5">
                The Vietnamese market is at the forefront of blockchain innovation, pioneering a new era of technology.
            </div>`,
    incubationContent: ` <div>
                            We incubate <span class="highlight">talented teams</span> with exceptional individuals, and provide them with the tools and resources needed to <span class="highlight">create a lasting impact.</span>
                        </div>`,
    cyballPJ: [
            "CyBall is a cyberpunk, football-themed web3 game with innovative blockchain technology and competitive gameplay where players can earn rewards.",
            "Backed by <span class='highlight'>BITKRAFT, Animoca Brands, Kingsway</span> among others.",
        ],
    ancient8Pj: [
        "GameFi infrastructure builder with a focus on software, community and guild.",
        "<span class='highlight'>$10M</span> fund raised from <span class='highlight'>Dragonfly Capital, Pantera, Makers Fund</span> among others.",
    ],
    media: [
        {
            title: "5M",
            des: "Monthly traffic",
          },
          {
            title: "1.7M",
            des: "Monthly Users",
          },
          {
            title: "Top 1 <br/> Blockchain <br/> Media",
            des: "in Vietnam",
          },
          {
            title: "Top 8 <br> Finance Media <br> in Vietnam",
            des: "in Vietnam",
          },
    ],
    publication: {
        subtitle: 'We provide institutional-grade research publications to report on all emerging trends within crypto.',
        marketReport: 'MARKET REPORT',
        indepthResearch: 'IN-DEPTH RESEARCH',
    },
    emailTitle: `let's seize <span class="text-stroke" style="--width: 2px"> this</span><br />
                <span class="text-stroke" style="--width: 2px">opportunity</span> together.`,
    highlightedProject: `highlighted <span class="text-stroke font-extrabold">project</span>`,
    portfolioPartners: `<span class="text-white none-stroke">PORTFOLIO</span> & PARTNER`,
    listLogos: [
        {
          name: "A8",
          imgLink: "./img/logos/A8.png",
          text: "Ancient8 develops the infrastructure for GameFi, with a focus on software and community. They help players and communities worldwide connect with the most innovative games, and enable everyone to build and play in the Metaverse.",
          websiteLink: "https://ancient8.gg/",
          id: null,
        },
        {
          name: "Alice",
          imgLink: "./img/logos/Alice.png",
          text: "My Neighbor Alice is a multiplayer builder game, where anyone can buy and own virtual islands, collect and build exciting items and meet new friends.",
          websiteLink: "https://www.myneighboralice.com/",
          id: null,
        },
         {
          name: "Cyball",
          imgLink: "./img/logos/Cyball.png",
          text: "CyBall is a cyberpunk football-themed, NFT-based web3 game with innovative blockchain technology and competitive gameplay where players can earn rewards.",
          websiteLink: "https://cyball.com/",
          id: null,
        },
         {
          name: "Chromia",
          imgLink: "./img/logos/Chromia.png",
          text: "Chromia is a public relational blockchain platform that allows people building decentralized apps easier in the real world, for a better world. The technology behind the Chromia blockchain is adapted from Postchain, a solution provided by Chromaway AB for enterprise clients.",
          websiteLink: "https://chromia.com/",
          id: null,
        },
         {
          name: "C98",
          imgLink: "./img/logos/C98.png",
          text: "Coin98 is all in one DeFi platform focusing on creating & developing ecosystem of DeFi protocols, applications on multiple blockchain.",
          websiteLink: "http://coin98.net/en",
          id: null,
        },
         {
          name: "GuildFi",
          imgLink: "./img/logos/GuildFi.png",
          text: "The interconnected ecosystem of games, communities, and NFT assets. Maximizing yields and enabling interoperability across the Metaverse.",
          websiteLink: "https://guildfi.com/",
          id: null,
        },
        {
          name: "Biconomy",
          imgLink: "./img/logos/Biconomy.png",
          text: "Biconomy makes blockchain transactions simple, enables gasless meta-transactions, instant cross-chain tranfers, easy layer 2 onboarding & zero failed transactions.",
          websiteLink: "https://www.biconomy.io/",
          id: null,
        },
         {
          name: "Serum",
          imgLink: "./img/logos/Serum.png",
          text: "Serum is a protocol for decentralized exchanges that brings unprecedented speed and low transaction costs to decentralized finance.",
          websiteLink: "https://www.projectserum.com/",
          id: null,
        },
        {
          name: "Dalarnia",
          imgLink: "./img/logos/Dalarnia.png",
          text: "Blending combat and dungeon crawling, Mines of Dalarnia delivers a fresh new entry to Web3 gaming genre, utilizing the power of blockchain technologies.",
          websiteLink: "https://www.minesofdalarnia.com/",
          id: null,
        },
         {
          name: "DeRace",
          imgLink: "./img/logos/DeRace.png",
          text: "DeRace is a play-to-earn NFT horse racing metaverse where you can participate in horse races, breed NFT horses with unique characteristics, build your own NFT hippodrome and make profit while doing it.",
          websiteLink: "https://derace.com/",
          id: null,
        },
         {
          name: "CLV",
          imgLink: "./img/logos/CLV.png",
          text: "CLV Chain is a Substrate-based specialized Layer 1 chain that is EVM compatible and cross-chain interoperable. Infrastructure made ready for scaling dApps in the multi-chain universe.",
          websiteLink: "https://clv.org/",
          id: null,
        },
        {
          name: "Polkastarter",
          imgLink: "./img/logos/Polkastarter.png",
          text: "Polkastarter is capital raising platform with highly-vetted ideas and teams you can trust. Supported by industry-leading creators and funds.",
          websiteLink: "https://polkastarter.com/",
          id: null,
        },
        {
          name: "BlockWallet",
          imgLink: "./img/logos/BlockWallet.png",
          text: "BlockWallet is the most private, non-custodial cryptocurrency wallet, using privacy-enhancing smart contracts to make your crypto transfers as private and secure as bank transfers.",
          websiteLink: "https://blockwallet.io/",
          id: null,
        },
        {
          name: "BreederDAO",
          imgLink: "./img/logos/BreederDAO.png",
          text: "BreederDAO is the go-to asset production factory for quality gaming assets of the Metaverse.",
          websiteLink: "https://www.breederdao.io/",
          id: null,
        },
        {
          name: "ChainofAlliance",
          imgLink: "./img/logos/ChainofAlliance.png",
          text: "Chain of Alliance is an RPG Gaming Multiverse where you can battle against other players, customize and level up characters, earn and collect NFTs.",
          websiteLink: "https://chainofalliance.com/",
          id: null,
        },
        // {
        //   name: "Chiliz",
        //   imgLink: "./img/logos/Chiliz.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Corite",
          imgLink: "./img/logos/Corite.png",
          text: "Corite empowers independent artists to release their fan power to the fullest, while getting their music on all major streaming services, such as Spotify, Apple Music, TikTok and YouTube.",
          websiteLink: "https://corite.com/",
          id: null,
        },
        {
          name: "DefiLand",
          imgLink: "./img/logos/DefiLand.png",
          text: "DeFiLand is a multi-chain agriculture-simulation game created to gamify Decentralized Finance.",
          websiteLink: "https://defiland.app/",
          id: null,
        },
        // {
        //   name: "Dfyn",
        //   imgLink: "./img/logos/Dfyn.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Divergence",
          imgLink: "./img/logos/Divergence.png",
          text: "Divergence is seamless, capital efficient, on-chain protocol for composable crypto options.",
          websiteLink: "https://www.divergence-protocol.com/",
          id: null,
        },
        {
          name: "Euler",
          imgLink: "./img/logos/Euler.png",
          text: "The main mission of Euler is democratizing the assets people can lend and borrow.",
          websiteLink: "https://www.euler.finance/",
          id: null,
        },
        {
          name: "Finblox",
          imgLink: "./img/logos/Finblox.png",
          text: "Finblox is a platform that helps crypto investors buy and earn high yield on their crypto assets.",
          websiteLink: "https://finblox.com/",
          id: null,
        },
        // {
        //   name: "FTX",
        //   imgLink: "./img/logos/FTX.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "GameFi",
          imgLink: "./img/logos/GameFi.png",
          text: "GameFi is an all-in-one discovery hub for games and metaverses. They also serve as one of the top gaming IDO platforms.",
          websiteLink: "https://gamefi.org/",
          id: null,
        },
        {
          name: "Gamestarter",
          imgLink: "./img/logos/Gamestarter.png",
          text: "Gamestarter is a blockchain-based crowdfunding platform that serves one of the largest industries in the world.",
          websiteLink: "https://igo.gamestarter.com/",
          id: null,
        },
        {
          name: "HeroesChained",
          imgLink: "./img/logos/HeroesChained.png",
          text: "Heroes Chained is a real time fantasy action RPG game, where the player becomes a Guild Master and gathers heroes.",
          websiteLink: "https://heroeschained.com/",
          id: null,
        },
        {
          name: "Lithium",
          imgLink: "./img/logos/Lithium.png",
          text: "Lithium Finance is a blockchain protocol building a collective intelligence algorithm to price the unpriced.",
          websiteLink: "https://testnet.lith.finance/",
          id: null,
        },
        {
          name: "manifold",
          imgLink: "./img/logos/manifold.png",
          text: "Manifold is making the connections to capital, propocols and people for DeFi They enable and provide access to high-value transaction pools on EVM compatible chains, through their SecureRPC infrastructure.",
          websiteLink: "https://www.manifoldfinance.com/",
          id: null,
        },
        // {
        //   name: "Mapsme",
        //   imgLink: "./img/logos/Mapsme.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Mercurial",
          imgLink: "./img/logos/Mercurial.png",
          text: "Mercurial is building the infrastructure for stable and pegged assets for Solana.",
          websiteLink: "https://www.mercurial.finance/",
          id: null,
        },
        // {
        //   name: "Mina",
        //   imgLink: "./img/logos/Mina.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Only1",
          imgLink: "./img/logos/Only1.png",
          text: "Only1 is the first web 3.0 social platform built on Solana. The platform offers an on-chain creator economy via the NFT marketplace and creator staking pools so that creators and viewers are rewarded fairly.",
          websiteLink: "https://only1.app/",
          id: null,
        },
        // {
        //   name: "Opium",
        //   imgLink: "./img/logos/Opium.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Pegaxy",
          imgLink: "./img/logos/Pegaxy.png",
          text: "Pegaxy is a racing game with futuristic mythological styling, built on Polygon. They pioneer in implementing the first in-game scholarship management feature.",
          websiteLink: "https://pegaxy.io/",
          id: null,
        },
        {
          name: "Portal",
          imgLink: "./img/logos/Portal.png",
          text: "Portal Defi is a decentralized financial platform that blends the best of Bitcoin and Layer 2.",
          websiteLink: "https://portaldefi.com/",
          id: null,
        },
        {
          name: "SkyArk",
          imgLink: "./img/logos/SkyArk.png",
          text: "SkyArk Chronicles is a Japanese fantasy role-playing game with Interoperable NFTs, developed by Binance-backed SkyArk Studio.",
          websiteLink: "https://www.skyarkchronicles.com/",
          id: null,
        },
        // {
        //   name: "splyt",
        //   imgLink: "./img/logos/splyt.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "SummonersArena",
          imgLink: "./img/logos/SummonersArena.png",
          text: "Summoners Arena is set out to be a multi-genre game universe made into a franchise, based on the antique lore of Summonia.",
          websiteLink: "https://summonersarena.io/",
          id: null,
        },
        // {
        //   name: "Swing",
        //   imgLink: "./img/logos/Swing.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Thetan",
          imgLink: "./img/logos/Thetan.png",
          text: "Thetan Arena is a MOBA eSports game based on blockchain technology. You can gather your friends, form a team, battle with others and earn money with just your skills.",
          websiteLink: "https://thetanarena.com/",
          id: null,
        },
        // {
        //   name: "TrustSwap",
        //   imgLink: "./img/logos/TrustSwap.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Web3auth",
          imgLink: "./img/logos/Web3auth.png",
          text: "Web3Auth, previously Torus, is a simple self-custodial auth infrastructure that supports the next 10 million users on Web3 wallet and dApps.",
          websiteLink: "https://web3auth.io/",
          id: null,
        },
        // {
        //   name: "WeStarter",
        //   imgLink: "./img/logos/WeStarter.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
      ],
}
