export const vi = {
    listFacts: [
        "Việt Nam đứng đầu thế giới về mức độ tiếp nhận tiền mã hóa trong năm 2021, theo nghiên cứu từ cả Chainalysis và Finder.",
        "Về mức độ tiếp nhận DeFi, Việt Nam xếp hạng 2 toàn cầu, chỉ sau Hoa Kỳ.",
        "Việt Nam là quốc gia có số lượng người dùng ví Metamask hoạt động hàng tháng cao thứ 3 thế giới.",
        "Thành lập vào năm 2016, Coin68 hiện là tổ chức truyền thông về tiền mã hóa lớn nhất Việt Nam.",
        "Coin68.com đã có hơn 15.000 bài viết và đưa tin đế hàng triệu độc giả.",
        "Kyros Ventures cung cấp báo cáo thị trường định kỳ cùng các bài viết nghiên cứu chuyên sâu hàng tuần.",
        "Mỗi 6 tháng, Coin68 và Kyros Ventures thực hiện cuộc khảo sát quy mô nhất Việt Nam về thị trường tiền mã hóa.",
    ],
    listSection: [
        "Xin chào",
        'Đây là Kyros',
        'Các trụ cột',
        'Đội ngũ',
        'Liên hệ',
    ],
    nurture: `Chúng tôi ươm mầm <br>
            các <span class="text-stroke" style="--width: 2px">đội ngũ tài năng</span><br />
            để thúc đẩy<span class="text-stroke" style="--width: 2px"> làn sóng đổi mới</span> <br>
            blockchain tiếp theo.`,
    weAre: `chúng tôi là cánh cửa<br />
            để tiếp cận <span class="text-stroke" style="--width: 2px">VIỆT NAM</span>,<br />
            thị trường tiền điện tử<br />
            <span class="text-stroke" style="--width: 2px">phát triển nhanh nhất</span> thế giới`,
    ourPillarTitle: 'CÁC <span class="text-stroke font-extrabold" style="--width: 2px">TRỤ CỘT</span>',
    network: `<div class="mb-5">
                Với mạng lưới đối tác tiền mã hóa phủ sóng rộng nhất <span class="underline highlight"><a href="https://vcmr.kyros.ventures/h1-2022-en/" target="_blank">VIỆT NAM</a></span>,
                chúng tôi có thể dễ dàng giúp dự án tiếp cận đến một trong những thị trường năng động nhất trên thế giới.
                <br> 
              </div>
            <div class="mt-5">
              Việt Nam được đánh giá là quốc gia đi đầu về tiến bộ blockchain, tiên phong trong trào lưu công nghệ mới.
            </div>`,
    incubationContent: `<div>
                            Chúng tôi ươm mầm những <span class="highlight">đội ngũ tài năng</span> với nhiều cá nhân xuất chúng, đồng thời cung cấp cho họ các công cụ và nguồn lực cần thiết để 
                            <span class="highlight">kiến tạo giải pháp bền vững</span> cho xã hội.
                        </div>`,
                        
    cyballPJ: [
        "CyBall là một trò chơi web3 theo chủ đề bóng đá, với công nghệ blockchain sáng tạo và lối chơi cạnh tranh, nơi người chơi có thể kiếm được phần thưởng.",
        "Dự án được đầu tư bởi <span class='highlight'>BITKRAFT, Animoca Brands, Kingsway</span> và các quỹ khác.",
    ],
    ancient8Pj: [
        "Nhà phát triển cơ sở hạ tầng GameFi tập trung vào phần mềm, cộng đồng và guild.",
        "Dự án đã huy động được <span class='highlight'>10 triệu USD</span> từ <span class='highlight'>Dragonfly Capital, Pantera, Makers Fund</span> và các quỹ khác.",
    ],
    media: [
        {
            title: "5 triệu",
            des: "Lượt truy cập <br> hàng tháng",
          },
          {
            title: "1.7 triệu",
            des: "Người dùng <br> hàng tháng",
          },
          {
            title: "Trang truyền thông <br/> Blockchain <br/> hàng đầu",
            des: "Việt Nam",
          },
          {
            title: "Top 8 trang<br> truyền thông <br> tài chính",
            des: "tại Việt Nam",
          },
    ],
    publication: {
        subTitle: 'Chúng tôi cung cấp các báo cáo nghiên cứu cấp tổ chức về tất cả các xu hướng tiền mã hóa mới nổi.',
        marketReport: 'BÁO CÁO THỊ TRƯỜNG',
        indepthResearch: 'NGHIÊN CỨU CHUYÊN SÂU',

    },
    emailTitle: `Hãy cùng nhau<br />
                <span class="text-stroke" style="--width: 2px">nắm lấy cơ hội này.</span>`,
    highlightedProject: `DỰ ÁN <span class="text-stroke font-extrabold">NỔI BẬT</span>`,
    portfolioPartners: `<span class="text-white none-stroke">DANH MỤC</span> & ĐỐI TÁC`,
    listLogos: [
        {
          name: "A8",
          imgLink: "./img/logos/A8.png",
          text: "Ancient8 phát triển cơ sở hạ tầng cho GameFi với trọng tâm là phần mềm và cộng đồng. Họ giúp người chơi và cộng đồng trên toàn thế giới kết nối với những tựa game sáng tạo nhất, đồng thời cho phép mọi người xây dựng và vui chơi trong Metaverse.",
          websiteLink: "https://ancient8.gg/",
          id: null,
        },
        {
          name: "Alice",
          imgLink: "./img/logos/Alice.png",
          text: "My Neighbor Alice là một trò chơi xây dựng, nơi bất kỳ ai cũng có thể mua và sở hữu các hòn đảo ảo, thu thập và xây dựng các vật phẩm thú vị cũng như gặp gỡ những người bạn mới.",
          websiteLink: "https://www.myneighboralice.com/",
          id: null,
        },
         {
          name: "Cyball",
          imgLink: "./img/logos/Cyball.png",
          text: "CyBall là một trò chơi web3 dựa trên NFT theo chủ đề bóng đá cyberpunk với công nghệ blockchain và lối chơi cạnh tranh, nơi người chơi có thể kiếm được phần thưởng.",
          websiteLink: "https://cyball.com/",
          id: null,
        },
         {
          name: "Chromia",
          imgLink: "./img/logos/Chromia.png",
          text: "Chromia là một nền tảng blockchain công cộng cho phép mọi người xây dựng các ứng dụng phi tập trung dễ dàng hơn trong thế giới thực, vì một thế giới tốt đẹp hơn. Công nghệ đằng sau blockhain Chromia được kế thừa từ Postchain, một giải pháp do Chromaway AB cung cấp cho khách hàng doanh nghiệp.",
          websiteLink: "https://chromia.com/",
          id: null,
        },
         {
          name: "C98",
          imgLink: "./img/logos/C98.png",
          text: "Coin98 là nền tảng DeFi tất cả trong một, tập trung vào việc tạo và phát triển hệ sinh thái của các giao thức DeFi và ứng dụng trên nhiều blockchain.",
          websiteLink: "http://coin98.net/en",
          id: null,
        },
         {
          name: "GuildFi",
          imgLink: "./img/logos/GuildFi.png",
          text: "Một hệ sinh thái trò chơi, cộng đồng và nội dung NFT được kết nối với nhau. Tối đa hóa sản lượng và cho phép khả năng tương tác trên Metaverse.",
          websiteLink: "https://guildfi.com/",
          id: null,
        },
        {
          name: "Biconomy",
          imgLink: "./img/logos/Biconomy.png",
          text: "Biconomy giúp các giao dịch blockchain trở nên đơn giản, cho phép meta-transaction không tốn gas, chuyển liên chuỗi tức thì, đưa các dự án tham gia layer 2 dễ dàng và không có giao dịch thất bại.",
          websiteLink: "https://www.biconomy.io/",
          id: null,
        },
         {
          name: "Serum",
          imgLink: "./img/logos/Serum.png",
          text: "Serum là một giao thức dành cho các sàn giao dịch phi tập trung mang lại tốc độ nhanh chưa từng có và chi phí giao dịch thấp cho các nền tài chính phi tập trung.",
          websiteLink: "https://www.projectserum.com/",
          id: null,
        },
        {
          name: "Dalarnia",
          imgLink: "./img/logos/Dalarnia.png",
          text: "Kết hợp chiến đấu và thu thập vật phẩm trong hang tối, Mines of Dalarnia mang đến một lựa chọn mới lạ cho thể loại game Web3, tận dụng sức mạnh của công nghệ blockchain.",
          websiteLink: "https://www.minesofdalarnia.com/",
          id: null,
        },
         {
          name: "DeRace",
          imgLink: "./img/logos/DeRace.png",
          text: "DeRace là một metaverse đua ngựa NFT chơi để kiếm tiền, nơi bạn có thể tham gia vào các cuộc đua ngựa, lai tạo những con ngựa NFT với các đặc điểm độc đáo, xây dựng trường đua NFT của riêng bạn và kiếm lợi nhuận từ đó.",
          websiteLink: "https://derace.com/",
          id: null,
        },
         {
          name: "CLV",
          imgLink: "./img/logos/CLV.png",
          text: "Chuỗi CLV là chuỗi layer 1 chuyên biệt xây trên Substrate tương thích với EVM và có thể tương tác xuyên chuỗi. Cơ sở hạ tầng của CLV đã sẵn sàng để mở rộng các dApp trong vũ trụ đa chuỗi.",
          websiteLink: "https://clv.org/",
          id: null,
        },
        {
          name: "Polkastarter",
          imgLink: "./img/logos/Polkastarter.png",
          text: "Polkastarter là nền tảng huy động vốn với các ý tưởng và đội ngũ được đánh giá cao mà bạn có thể tin tưởng. Được hỗ trợ bởi những người kiến tạo và quỹ đầu ngành.",
          websiteLink: "https://polkastarter.com/",
          id: null,
        },
        {
          name: "BlockWallet",
          imgLink: "./img/logos/BlockWallet.png",
          text: "BlockWallet là ví tiền mã hóa riêng tư nhất, không lưu ký, sử dụng các hợp đồng thông minh tăng cường quyền riêng tư để thực hiện chuyển tiền mã hóa của bạn riêng tư và an toàn như chuyển khoản ngân hàng.",
          websiteLink: "https://blockwallet.io/",
          id: null,
        },
        {
          name: "BreederDAO",
          imgLink: "./img/logos/BreederDAO.png",
          text: "BreederDAO là nhà máy sản xuất nội dung chuyên dụng cho các tài sản trong game chất lượng của Metaverse.",
          websiteLink: "https://www.breederdao.io/",
          id: null,
        },
        {
          name: "ChainofAlliance",
          imgLink: "./img/logos/ChainofAlliance.png",
          text: "Chain of Alliance là một RPG Gaming Multiverse, nơi bạn có thể chiến đấu với những người chơi khác, tùy chỉnh và thăng cấp nhân vật cũng như tìm kiếm và thu thập NFT.",
          websiteLink: "https://chainofalliance.com/",
          id: null,
        },
        // {
        //   name: "Chiliz",
        //   imgLink: "./img/logos/Chiliz.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Corite",
          imgLink: "./img/logos/Corite.png",
          text: "Corite trao quyền cho các nghệ sĩ độc lập bằng việc giải phóng tối đa sức mạnh của người hâm mộ, đồng thời đưa âm nhạc của họ lên tất cả các dịch vụ phát sóng trực tuyến chính, chẳng hạn như Spotify, Apple Music, TikTok và YouTube.",
          websiteLink: "https://corite.com/",
          id: null,
        },
        {
          name: "DefiLand",
          imgLink: "./img/logos/DefiLand.png",
          text: "DeFiLand là một trò chơi mô phỏng nông nghiệp đa chuỗi được tạo ra để game hóa Tài chính phi tập trung.",
          websiteLink: "https://defiland.app/",
          id: null,
        },
        // {
        //   name: "Dfyn",
        //   imgLink: "./img/logos/Dfyn.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Divergence",
          imgLink: "./img/logos/Divergence.png",
          text: "Divergence là giao thức trên chuỗi liền mạch và hiệu quả vốn dành cho các quyền chọn tiền mã hóa có thể kết hợp.",
          websiteLink: "https://www.divergence-protocol.com/",
          id: null,
        },
        {
          name: "Euler",
          imgLink: "./img/logos/Euler.png",
          text: "Nhiệm vụ chính của Euler là dân chủ hóa các tài sản mà mọi người có thể cho vay và mượn.",
          websiteLink: "https://www.euler.finance/",
          id: null,
        },
        {
          name: "Finblox",
          imgLink: "./img/logos/Finblox.png",
          text: "Finblox là một nền tảng giúp các nhà đầu tư tiền mã hóa mua và kiếm được lợi nhuận cao từ tài sản tiền mã hóa của họ.",
          websiteLink: "https://finblox.com/",
          id: null,
        },
        // {
        //   name: "FTX",
        //   imgLink: "./img/logos/FTX.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "GameFi",
          imgLink: "./img/logos/GameFi.png",
          text: "GameFi là một trung tâm khám phá tất cả các trò chơi và metaverse. Họ cũng đóng vai trò là một trong những nền tảng IDO về gaming hàng đầu.",
          websiteLink: "https://gamefi.org/",
          id: null,
        },
        {
          name: "Gamestarter",
          imgLink: "./img/logos/Gamestarter.png",
          text: "Gamestarter là một nền tảng huy động vốn cộng đồng dựa trên blockchain phục vụ một trong những ngành công nghiệp lớn nhất trên thế giới.",
          websiteLink: "https://igo.gamestarter.com/",
          id: null,
        },
        {
          name: "HeroesChained",
          imgLink: "./img/logos/HeroesChained.png",
          text: "Heroes Chained là một trò chơi nhập vai hành động giả tưởng thời gian thực, nơi người chơi có thể trở thành một Guild Master và tập hợp các anh hùng.",
          websiteLink: "https://heroeschained.com/",
          id: null,
        },
        {
          name: "Lithium",
          imgLink: "./img/logos/Lithium.png",
          text: "Lithium Finance là một giao thức blockchain xây dựng một thuật toán trí tuệ tập thể để định giá các tài sản chưa được định giá.",
          websiteLink: "https://testnet.lith.finance/",
          id: null,
        },
        {
          name: "manifold",
          imgLink: "./img/logos/manifold.png",
          text: "Manifold đang tạo kết nối với vốn, các giao thức và con người cho DeFi. Họ cho phép và cung cấp quyền truy cập vào các nhóm giao dịch giá trị cao trên các chuỗi tương thích EVM, thông qua cơ sở hạ tầng SecureRPC của họ.",
          websiteLink: "https://www.manifoldfinance.com/",
          id: null,
        },
        // {
        //   name: "Mapsme",
        //   imgLink: "./img/logos/Mapsme.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Mercurial",
          imgLink: "./img/logos/Mercurial.png",
          text: "Mercurial đang xây dựng cơ sở hạ tầng cho các tài sản ổn định và cố định cho Solana.",
          websiteLink: "https://www.mercurial.finance/",
          id: null,
        },
        // {
        //   name: "Mina",
        //   imgLink: "./img/logos/Mina.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Only1",
          imgLink: "./img/logos/Only1.png",
          text: "Only1 là nền tảng xã hội web 3.0 đầu tiên được xây dựng trên Solana. Nền tảng cung cấp nền kinh tế cho người sáng tạo nội dung trên chuỗi thông qua thị trường NFT và các nhóm hỗ trợ nhà sáng tạo, giúp cả nhà sáng tạo và người xem đều được tưởng thưởng một cách công bằng.",
          websiteLink: "https://only1.app/",
          id: null,
        },
        // {
        //   name: "Opium",
        //   imgLink: "./img/logos/Opium.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Pegaxy",
          imgLink: "./img/logos/Pegaxy.png",
          text: "Pegaxy là một trò chơi đua ngựa với phong cách thần thoại tương lai, được xây dựng trên Polygon. Họ đi tiên phong trong việc triển khai tính năng quản lý học bổng trong game.",
          websiteLink: "https://pegaxy.io/",
          id: null,
        },
        {
          name: "Portal",
          imgLink: "./img/logos/Portal.png",
          text: "Portal Defi là một nền tảng tài chính phi tập trung kết hợp những gì tốt nhất của Bitcoin và Layer 2.",
          websiteLink: "https://portaldefi.com/",
          id: null,
        },
        {
          name: "SkyArk",
          imgLink: "./img/logos/SkyArk.png",
          text: "SkyArk Chronicles là một trò chơi nhập vai giả tưởng của Nhật Bản với các NFT có thể tương tác, được phát triển bởi SkyArk Studio do Binance hậu thuẫn.",
          websiteLink: "https://www.skyarkchronicles.com/",
          id: null,
        },
        // {
        //   name: "splyt",
        //   imgLink: "./img/logos/splyt.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "SummonersArena",
          imgLink: "./img/logos/SummonersArena.png",
          text: "Summoners Arena được thiết lập là một vũ trụ trò chơi đa thể loại được nhượng quyền thương mại, dựa trên truyền thuyết cổ về Summonia.",
          websiteLink: "https://summonersarena.io/",
          id: null,
        },
        // {
        //   name: "Swing",
        //   imgLink: "./img/logos/Swing.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Thetan",
          imgLink: "./img/logos/Thetan.png",
          text: "Thetan Arena là một trò chơi MOBA eSports dựa trên công nghệ blockchain. Bạn có thể tập hợp bạn bè, thành lập một đội, chiến đấu với những người khác và kiếm tiền chỉ với kỹ năng của mình.",
          websiteLink: "https://thetanarena.com/",
          id: null,
        },
        // {
        //   name: "TrustSwap",
        //   imgLink: "./img/logos/TrustSwap.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
        {
          name: "Web3auth",
          imgLink: "./img/logos/Web3auth.png",
          text: "Web3Auth, trước đây là Torus, là một cơ sở hạ tầng xác thực không lưu ký đơn giản, hỗ trợ 10 triệu người dùng tiếp theo trên ví Web3 và dApps.",
          websiteLink: "https://web3auth.io/",
          id: null,
        },
        // {
        //   name: "WeStarter",
        //   imgLink: "./img/logos/WeStarter.png",
        //   text: "",
        //   websiteLink: "",
        //   id: null,
        // },
      ],
}